@startuml
left to right direction

actor Administrador
actor Jugador
actor Sistema

rectangle "Gestión de Equipos y Jugadores" {
    usecase "Registrar equipo" as UC1
    usecase "Añadir jugadores a equipo" as UC2
    usecase "Consultar lista de equipos y jugadores" as UC3
}

Administrador --> UC1
Administrador --> UC2
Administrador --> UC3
Jugador --> UC3

UC2 .> UC1 : <<include>>

@enduml
